# Generated by Django 3.1.1 on 2021-06-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Location_id', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Product_id', models.CharField(max_length=50, unique=True)),
                ('Quantity', models.IntegerField()),
                ('reserved_quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Movement_id', models.IntegerField(unique=True)),
                ('Quantity', models.IntegerField()),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.product')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='Manage.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manage.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='Product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Manage.product'),
        ),
    ]
